### ISSUE TITLE
请问老师如何得到数据集的训练样本和测试样本

### ISSUE THREAD

**Issue by Mary-HE** [summitgao/SAR_CD_GKSNet#3]
老师，可以讲解一下如何得到训练数据和测试数据的吗，谢谢老师

**Comment by summitgao** [comment]
你好，负责这个工作的同学毕业了，可以联系 王俊杰：[1091416535@qq.com](mailto:1091416535@qq.com)

**Comment by Mary-HE** [comment]
好的，谢谢老师
